### ISSUE TITLE
Add Hamilton norm and pooling script to relevant steps in LIMS

### ISSUE THREAD

**Issue by RasmusBurge-CG** [Clinical-Genomics/cg_lims#220]
Lims Issue
---------------

**Task 1**

---------------
**Work Flow:** 
-  WGS PCR free v5

**Protocol:** 
- TruSeq DNA PCR-free Library Prep

**Step:**
-  Aliquot Samples for Covaris

**Description:** 
Add Hamilton norm script.

- [x] Above is done

*Task2*

---------------
**Work Flow:** 
-  CG001 Genotyping

**Protocol:** 
- CG002 Genotyping

**Step:**
-  CG002 - Plate Setup MAF

**Description:** 
Add Hamilton norm script.

- [x] Above is done

*Task 3*

---------------
**Work Flow:** 
-  RNA v4

**Protocol:** 
- Normalization of RNA samples for sequencing

**Step:**
- Normalization of RNA samples for sequencing v1

- [ ] Above is done

**Comment by idalindegaard** [comment]
**Test for the Genotyping workflow**
Added the Hamilton normalization and pooling script and it created a file with correct values, see two screenshots below for file and the information that was used in LIMS:
<img width="987" alt="Screenshot 2023-01-04 at 13 48 27" src="https://user-images.githubusercontent.com/82438141/210559032-7642833a-2bdc-42b0-980c-2ec93bbf7888.png">
<img width="1404" alt="Screenshot 2023-01-04 at 13 49 03" src="https://user-images.githubusercontent.com/82438141/210559043-28cd2b83-8c79-4f59-b3ed-e67d381e26ee.png">
I double-checked that the source container barcodes were correct from the steps where they were registered. The samples that come in tubes have their respective LIMS ID's without the "ACC" in the beginning.
<img width="706" alt="Screenshot 2023-01-04 at 13 50 41" src="https://user-images.githubusercontent.com/82438141/210559050-148bd780-6301-4dbe-9878-450ec4c2cd26.png">

The script seems to work and can be used in production.

**Comment by idalindegaard** [comment]
Opened a new issue for the RNA v4 changes so I can close this issue. See #437
